all: my-cat my-grep my-zip my-unzip

my-cat: my-cat.c
	gcc -g -o my-cat my-cat.c -Wall -Werror -std=c99

my-grep: my-grep.c
	gcc -g -o my-grep my-grep.c -Wall -Werror -std=c99

my-zip: my-zip.c
	gcc -g -o my-zip my-zip.c -Wall -Werror -std=c99

my-unzip: my-unzip.c
	gcc -g -o my-unzip my-unzip.c -Wall -Werror -std=c99

clean:
	rm my-cat my-grep my-zip my-unzip
